project:
  labels:
    cost_center: "engineering"
    environment: "dev"
  additional_apis:
    - "container.googleapis.com"
    - "storage.googleapis.com"
    - "pubsub.googleapis.com"
  description : "apg"
  environment: "dev"

service_accounts:
  app:
    display_name: "Application Service Account"
    description: "Main application service account"
    roles:
      - "roles/storage.objectViewer"
      - "roles/logging.logWriter"
      - "roles/monitoring.metricWriter"
  cicd:
    display_name: "CI/CD Pipeline SA"
    description: "Service account for CI/CD operations"
    roles:
      - "roles/cloudbuild.builds.editor"
      - "roles/storage.admin"