org_id: "your-organization-id"         # Required: GCP Organization ID (e.g., "123456789012")
access_policy_title: "Custom Policy Title"
perimeter_name: "custom_perimeter_name"
perimeter_title: "custom_perimeter_name_title"
folder_id: ""  #folder under which all the projects will be put in perimeter
excluded_projects: ["projects/project_id"]

# --- Optional variables (will use defaults from vpcsc module if not specified) ---

#scopes:                                 # List of project resource names for policy scope
#  - "folders/foder_ID"                  # Example: "folders/1234567890"

#restricted_projects:                    # Asset search finds all project under a folder if manually you need to add projects  do it here.
#  - "projects/your-target-project-id"   # Example: "projects/1234567890"
#  - "projects/your-target-project-id"

# restricted_services:                  # Optional: Defaults to ["storage.googleapis.com", "bigquery.googleapis.com"]
#   - "storage.googleapis.com"
#   - "bigquery.googleapis.com"

allowed_ip_subnets:                   # Optional: Defaults to [""]
   - "34.79.169.228/32"
#allowed_members:                      # Optional: Defaults to []
#   - "user:user@domain.co.uk"
# egress_resources:                     # Optional: Defaults to []
#   - "projects/external-project-123"
# ingress_source_project: ""            # Optional: Defaults to "" (e.g. "projects/source-project-for-ingress")