org_id: "your-organization-id"         # Required: GCP Organization ID (e.g., "123456789012")
project_id: "your-target-project-id"    # Required: Project ID for the target project
access_policy_title: "Custom Policy Title"
perimeter_name: "custom_perimeter_name"
perimeter_title: "Custom Perimeter Title"


# --- Optional variables (will use defaults from vpcsc module if not specified) ---
# region: "europe-west2"
# access_policy_title: "Custom Policy Title"
# perimeter_name: "custom_perimeter_name"
# perimeter_title: "Custom Perimeter Title"

scopes:                                 # Required: List of project resource names for policy scope
  - "folders/foder_ID"                  # Example: "folders/1234567890" or "projects/your-project-id"

restricted_projects:                    # Required: TODO: use asset search find project resource list and add exclusion var to exclude
#  - "projects/your-target-project-id"   # Example: "projects/1234567890"
#  - "projects/your-target-project-id"

# restricted_services:                  # Optional: Defaults to ["storage.googleapis.com", "bigquery.googleapis.com"]
#   - "storage.googleapis.com"
#   - "bigquery.googleapis.com"

# allowed_ip_subnets:                   # Optional: Defaults to [""]
#   - "192.168.1.0/24"
# allowed_members:                      # Optional: Defaults to ["user:"]
#   - "user:example-user@yourdomain.com"
# egress_resources:                     # Optional: Defaults to []
#   - "projects/external-project-123"
# ingress_source_project: ""            # Optional: Defaults to "" (e.g. "projects/source-project-for-ingress")